name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
jobs:
  fake-run:
    runs-on: tenki-standard-autoscale
    steps:
      - name: Wait 10 minutes
        run: sleep 100 # 600 seconds = 10 minutes

      - name: Confirm end of fake run
        run: echo "Finished fake 10-minute job for test"
